export const TRACKS = [
  {
    id: 'analysis',
    number: '01',
    title: '商业分析',
    english: 'Business Analysis',
    color: 'blue',
    description: '把模糊问题转成指标、假设、证据和决策。',
    outcome: '完成后能搭指标树、拆漏斗、计算单位经济，并提出可验证建议。',
  },
  {
    id: 'gtm',
    number: '02',
    title: '海外GTM',
    english: 'Go-to-Market',
    color: 'red',
    description: '从市场选择、ICP和定位，一路走到渠道、实验与上市复盘。',
    outcome: '完成后能输出一页GTM画布，并判断Go、Iterate或Stop。',
  },
  {
    id: 'globalization',
    number: '03',
    title: '出海商业化',
    english: 'Global Commercialization',
    color: 'green',
    description: '连接商业模式、销售管线、伙伴、支付合规与跨文化执行。',
    outcome: '完成后能评估一项出海生意是否可卖、可交付、可回款、可复制。',
  },
];

export const LESSONS = [
  {
    id: 'problem-framing', trackId: 'analysis', order: 1, duration: 35, level: '基础',
    title: '问题定义与假设树',
    summary: '先确认要做什么决策，再拆原因；不要一上来就找数据。',
    keywords: ['问题定义', '假设树', 'MECE', '决策'],
    outcomes: ['写出决策问题而非研究主题', '区分现象、原因和行动', '形成可证伪的假设'],
    sections: [
      { title: '从决策开始', paragraphs: ['好的商业分析不是“把数据都看一遍”，而是帮助某个角色在某个时间点做出选择。'], bullets: ['决策者是谁', '要选择什么', '成功标准是什么', '最晚何时需要答案'] },
      { title: '问题陈述模板', paragraphs: ['在指定市场、客群和时间范围内，某项指标发生了什么变化；我们需要判断主要原因，并决定优先采取哪项行动。'], bullets: ['范围明确', '指标可观察', '原因待验证', '行动可比较'] },
      { title: '假设的质量', paragraphs: ['假设必须能被证据推翻。把“市场不好”改成“目标客群需求下降、竞争加剧或内部供给不足”。'], bullets: ['先列高影响假设', '为每个假设指定证据', '设置停止继续深挖的标准'] },
    ],
    toolkit: ['决策问题', '问题树', '假设—证据表', '优先级矩阵'],
    exercise: { title: '把抱怨改成分析问题', prompt: '某海外业务负责人说：“新市场上线三个月，增长不及预期。”请写出一个决策问题、三条一级假设和每条假设的首个验证指标。', deliverable: '一页假设树，控制在15分钟内。' },
  },
  {
    id: 'metric-system', trackId: 'analysis', order: 2, duration: 45, level: '核心',
    title: '指标树、漏斗与诊断',
    summary: '把结果指标拆成可行动的领先指标，找到真正需要干预的位置。',
    keywords: ['指标树', '漏斗', '领先指标', '归因'],
    outcomes: ['搭建结果指标树', '识别漏斗瓶颈', '区分相关性与因果'],
    sections: [
      { title: '指标树', paragraphs: ['从业务结果向下拆：收入通常可拆为流量×转化率×客单价；但每层必须符合具体业务。'], bullets: ['结果指标用于判断成败', '领先指标用于提前干预', '护栏指标防止局部优化伤害整体'] },
      { title: '漏斗诊断', paragraphs: ['比较绝对量、转化率、时间趋势和分群差异。不要只看总平均。'], bullets: ['先确认口径和数据质量', '定位变化发生在哪一层', '按渠道、客群、地区和产品分解'] },
      { title: '归因边界', paragraphs: ['同期增长不等于某个动作造成增长。没有对照实验时，应表述为“动作与结果同时发生，并有机制证据支持”。'], bullets: ['记录其他同时变化', '寻找前后趋势和对照组', '明确可控动作与不可控因素'] },
    ],
    toolkit: ['北极星指标', '指标树', '转化漏斗', '分群分析', '护栏指标'],
    exercise: { title: '搭建市场进入漏斗', prompt: '为一个新上线的B2B平台设计“触达→注册→激活→首单→复购”漏斗，并为每层写一个诊断维度和一个护栏指标。', deliverable: '漏斗图＋指标定义表。' },
  },
  {
    id: 'unit-economics', trackId: 'analysis', order: 3, duration: 50, level: '核心',
    title: '单位经济、实验与决策',
    summary: '增长是否值得扩大，最终要回到单笔贡献、获客回收和可重复性。',
    keywords: ['单位经济', 'CAC', 'LTV', '贡献毛利', '实验'],
    outcomes: ['计算单笔贡献毛利', '理解LTV/CAC及回收期', '设计带止损条件的实验'],
    sections: [
      { title: '单位经济', paragraphs: ['GMV不是收入，收入也不是贡献毛利。先明确平台从一笔交易真正获得什么，再扣除随交易变化的成本。'], bullets: ['净收入＝交易额×变现率＋增值收入', '贡献毛利＝净收入－渠道、支付、履约等可变成本', '固定成本用于判断规模后的盈亏'] },
      { title: 'CAC与LTV', paragraphs: ['LTV/CAC只有在留存、毛利和时间口径一致时才有意义。早期业务应同时看获客回收期。'], bullets: ['按渠道分开计算CAC', '用贡献毛利而非GMV估算LTV', '做关键变量敏感性分析'] },
      { title: '实验闸门', paragraphs: ['实验要预先定义继续、迭代和停止条件，避免看到任何正向数字就扩大投入。'], bullets: ['一个核心假设', '一个主要指标', '必要样本和周期', '最大损失上限'] },
    ],
    toolkit: ['单笔UE', 'LTV/CAC', '回收期', '敏感性分析', 'Go/Iterate/Stop'],
    exercise: { title: '判断是否扩大投放', prompt: '某渠道CAC为80元，首单贡献毛利30元，90天复购率35%，复购单贡献毛利25元。请说明还缺哪些信息，并设计下一轮验证闸门。', deliverable: '计算思路＋Go/Iterate/Stop建议。' },
  },
  {
    id: 'market-selection', trackId: 'gtm', order: 1, duration: 45, level: '基础',
    title: '市场选择与进入顺序',
    summary: '大市场不一定是好首站；首站应兼顾需求、能力、成本和验证效率。',
    keywords: ['市场选择', 'TAM', '进入顺序', '风险'],
    outcomes: ['建立市场评分框架', '识别公司可复用优势', '设置进入前提'],
    sections: [
      { title: '五个比较维度', paragraphs: ['需求规模只是一个维度，还要比较竞争、进入能力、合规及单位经济。'], bullets: ['需求强度和增长', '竞争与替代方案', '供应、渠道和品牌能力', '合规与履约复杂度', '验证成本和回收潜力'] },
      { title: '首站逻辑', paragraphs: ['首站不是十年终局，而是最快验证核心模式的地方。'], bullets: ['可获取第一批用户', '可获得核心供给', '失败成本可控', '成功后能复制'] },
      { title: '证据等级', paragraphs: ['桌面数据、访谈意愿、书面合作、真实点击和真实交易的证据强度不同。'], bullets: ['不把合作意向写成资源已到位', '不把市场规模写成产品需求', '不把问卷兴趣写成付费意愿'] },
    ],
    toolkit: ['市场评分卡', '证据等级', '进入前提', '风险清单'],
    exercise: { title: '选择首个海外市场', prompt: '产品准备进入A、B、C三个市场。请设计不超过8项的评分卡，并说明哪些条件是一票否决项。', deliverable: '评分卡＋推荐顺序＋待验证信息。' },
  },
  {
    id: 'icp-positioning', trackId: 'gtm', order: 2, duration: 45, level: '核心',
    title: 'ICP、场景与定位',
    summary: '不要服务“所有海外用户”；先找最痛、最易触达、最愿付费的一群人。',
    keywords: ['ICP', '用户画像', '场景', '定位', '价值主张'],
    outcomes: ['定义可执行ICP', '区分用户画像与购买者', '写出定位陈述'],
    sections: [
      { title: 'B2B ICP', paragraphs: ['ICP描述最适合公司的企业，不只是联系人画像。'], bullets: ['行业与规模', '业务场景和触发事件', '现有替代方案', '购买能力和复杂度', '排除条件'] },
      { title: '购买委员会', paragraphs: ['使用者、业务负责人、预算所有者、技术、法务和采购关注点不同。'], bullets: ['谁感到痛', '谁获得价值', '谁承担风险', '谁能否决'] },
      { title: '定位模板', paragraphs: ['对于某类目标客户，在某个高优先场景中，我们提供某项结果；相比替代方案，差异来自可验证能力。'], bullets: ['不堆功能', '结果必须可衡量', '差异不能只写“更智能”'] },
    ],
    toolkit: ['ICP卡', 'JTBD', '利益相关方地图', '定位陈述'],
    exercise: { title: '收窄目标客群', prompt: '一款跨境费用管理产品准备进入东南亚。请定义一个首期ICP、购买委员会和三条排除条件。', deliverable: '一页ICP与定位卡。' },
  },
  {
    id: 'gtm-system', trackId: 'gtm', order: 3, duration: 55, level: '核心',
    title: '渠道、定价、本地化与上市',
    summary: 'GTM是收入系统，不是一份传播排期。',
    keywords: ['渠道', '定价', '本地化', 'Launch', 'GTM'],
    outcomes: ['组合获客和销售路径', '设计本地化优先级', '建立上市与复盘机制'],
    sections: [
      { title: '路径设计', paragraphs: ['产品导向、销售导向、伙伴导向和内容导向适合不同客单价与购买复杂度。'], bullets: ['渠道必须匹配ICP', '计算渠道经济性', '明确线索到成交的责任边界'] },
      { title: '定价与包装', paragraphs: ['价格表达价值，也决定销售复杂度。进入新市场时要区分币种、税、支付习惯和合同周期。'], bullets: ['按价值与成本设边界', '准备基础包与升级路径', '避免永久依赖折扣'] },
      { title: '本地化层级', paragraphs: ['翻译只是最低层。更深的本地化包括产品、定价、渠道、合规、服务和品牌信任。'], bullets: ['先处理阻断交易的本地化', '把文化偏好与法规要求分开', '用实验决定深度'] },
      { title: '上市节奏', paragraphs: ['从Smoke test到小规模MVP，再到正式Launch；每阶段只回答有限问题。'], bullets: ['领先指标', '护栏指标', '责任人', '复盘与资源释放条件'] },
    ],
    toolkit: ['GTM画布', '渠道矩阵', '定价包装', '本地化清单', 'Launch闸门'],
    exercise: { title: '制作一页GTM画布', prompt: '为一款B2B分析工具进入德国市场设计ICP、定位、渠道、定价假设、MVP和90天指标。', deliverable: '一页GTM画布，明确三条停止条件。' },
  },
  {
    id: 'business-model', trackId: 'globalization', order: 1, duration: 45, level: '基础',
    title: '商业模式与伙伴生态',
    summary: '先说明谁付钱、为什么付、谁交付，再讨论如何扩大。',
    keywords: ['商业模式', '伙伴', '价值链', '收入模式'],
    outcomes: ['画清价值链与资金流', '比较直销和伙伴模式', '设计利益分配'],
    sections: [
      { title: '商业模式四问', paragraphs: ['客户、价值、交付和收入必须连成闭环。'], bullets: ['谁是客户与使用者', '解决什么高价值问题', '依赖哪些能力交付', '如何收费并持续获利'] },
      { title: '伙伴角色', paragraphs: ['渠道、供应、技术、履约和品牌伙伴承担不同漏斗环节。'], bullets: ['伙伴带来什么独特资源', '利益如何计算', '数据和客户归属', '失败时谁承担责任'] },
      { title: '避免伪协同', paragraphs: ['“集团资源可复用”只有在资源所有者、接入成本和书面承诺清晰时才进入模型。'], bullets: ['意向不计入收入', '资源置换也要估值', '设置试点范围和退出机制'] },
    ],
    toolkit: ['商业模式画布', '价值链', '伙伴分工表', '利益分配'],
    exercise: { title: '设计伙伴合作', prompt: '一个新品牌希望借本地内容平台获客、由自己完成交易。请设计双方分工、计费、数据归因和试点闸门。', deliverable: '伙伴方案一页纸。' },
  },
  {
    id: 'pipeline-commercial', trackId: 'globalization', order: 2, duration: 50, level: '核心',
    title: '销售管线、预测与账户计划',
    summary: '把“聊过很多客户”变成可审查的商机、下一步和预测。',
    keywords: ['销售管线', '预测', '账户计划', '顾问式销售'],
    outcomes: ['定义商机阶段', '计算加权管线', '制定账户增长计划'],
    sections: [
      { title: '商机阶段', paragraphs: ['每个阶段必须有客户行为和退出条件。销售做了动作，不代表客户向前推进。'], bullets: ['目标账户', '已发现有效问题', '方案获得认可', '商务与风险确认', '签约与上线'] },
      { title: '预测', paragraphs: ['加权管线用于组合判断，不代替逐单判断。Commit必须有明确客户承诺。'], bullets: ['金额和时间口径一致', '记录阻碍和下一步', '复盘预测偏差'] },
      { title: '账户计划', paragraphs: ['存量账户增长来自目标、机会、关系、风险和行动的组合。'], bullets: ['客户业务目标', '价值实现证据', '利益相关方', '风险和增长机会', '双方下一步'] },
    ],
    toolkit: ['管线阶段', '加权预测', '发现问题', '账户计划', 'QBR'],
    exercise: { title: '建立轻量管线', prompt: '为10个虚构目标账户建立管线，定义每个阶段的退出条件，并给出本月Commit与Best Case。', deliverable: '管线表＋300字预测说明。' },
  },
  {
    id: 'payments-compliance', trackId: 'globalization', order: 3, duration: 55, level: '核心',
    title: '跨境支付、合规与执行',
    summary: '出海方案必须能收款、结算、履约并处理风险。',
    keywords: ['跨境支付', 'KYC', 'KYB', 'GDPR', '履约'],
    outcomes: ['理解支付与结算链路', '识别基础合规责任', '设计跨文化执行机制'],
    sections: [
      { title: '资金流', paragraphs: ['区分消费者付款、商户收款、换汇、结算和对外付款。每个环节都有费率、时效和失败原因。'], bullets: ['授权与捕获', '结算与对账', '退款与拒付', '多币种与FX'] },
      { title: '合规边界', paragraphs: ['业务人员要能识别何时需要法务、风控和合规介入，但不能替代专业判断。'], bullets: ['KYC/KYB与受益所有人', 'AML与制裁筛查', '隐私和跨境数据', '消费者保护与税务'] },
      { title: '跨文化执行', paragraphs: ['本地团队、总部中台和伙伴之间需要清晰的决策权、升级路径和服务标准。'], bullets: ['语言和时区', '书面沟通习惯', '本地节假日和劳动规则', '异常履约责任'] },
    ],
    toolkit: ['资金流图', '合规清单', 'RACI', '风险登记册', 'SLA'],
    exercise: { title: '处理商户上线受阻', prompt: '一家跨境商户因KYB材料不完整无法开通收款，同时担心错过大促。请给出客户沟通、内部协作和风险控制方案。', deliverable: '15分钟口头回答＋行动清单。' },
  },
];

export const QUESTION_TYPES = {
  interview: '面试题',
  written: '笔试题',
  scenario: '真实商业场景',
};

export const QUESTIONS = [
  {
    id: 'q-growth-drop', trackId: 'analysis', type: 'interview', difficulty: '基础', duration: 10,
    title: '新市场增长突然下降，如何分析？',
    context: '某在线服务进入新市场后三个月，周新增付费客户下降20%，团队认为是广告疲劳。',
    prompt: '请说明你的分析步骤、需要的数据和优先行动。',
    requirements: ['先核对口径和数据质量', '至少拆到流量、转化、价格／产品和履约', '说明如何判断广告疲劳是否成立'],
    framework: ['重述决策问题与范围', '检查数据完整性、季节和统计变化', '搭建新增付费客户指标树', '按渠道、客群、设备、地区和周期分解', '为前三条假设指定验证证据', '提出短期修复和长期实验，并设置护栏'],
    pitfalls: ['直接接受“广告疲劳”结论', '只报更多指标，不形成优先级', '把同期变化当因果'],
  },
  {
    id: 'q-metric-tree', trackId: 'analysis', type: 'written', difficulty: '核心', duration: 30,
    title: '为B2B产品搭建增长指标树',
    context: '一家B2B协作产品计划提升存量客户收入，但不同团队对“增长”定义不一致。',
    prompt: '请设计结果指标、领先指标、护栏指标及数据看板结构。',
    requirements: ['区分Logo和收入留存', '覆盖采用、价值、续约与增购', '说明指标口径和负责人'],
    framework: ['北极星：存量客户NRR或贡献毛利', '拆分续约、收缩、扩张', '领先指标：激活、关键功能采用、席位深度、活跃团队、价值里程碑', '风险指标：工单、情绪、付款、关键联系人流失', '护栏：服务成本、折扣、客诉', '按客户分层和生命周期展示'],
    pitfalls: ['只看登录次数', '将满意度直接等同续约', '指标没有行动责任人'],
  },
  {
    id: 'q-unit-economics', trackId: 'analysis', type: 'scenario', difficulty: '进阶', duration: 35,
    title: 'GMV增长但业务更亏，要不要继续？',
    context: '一个新渠道带来50%的GMV增长，但退款率、补贴和客服成本同步上升。负责人希望立刻加预算。',
    prompt: '请建立单位经济判断，并给出Go、Iterate或Stop建议。',
    requirements: ['不以GMV单独判断', '列出单笔收入和可变成本', '给出下一轮实验闸门'],
    framework: ['计算净收入和单笔贡献毛利', '按渠道与客群分层', '纳入退款窗口和客服时长', '估算复购贡献与CAC回收期', '识别是否为低质量用户或履约问题', '设置预算上限、样本、主要指标和停止条件'],
    pitfalls: ['把收入等于GMV', '用长期LTV掩盖短期负贡献', '没有最大损失上限'],
  },
  {
    id: 'q-market-choice', trackId: 'gtm', type: 'interview', difficulty: '基础', duration: 12,
    title: '如何选择第一个海外市场？',
    context: '一家中国B2B软件公司在三个国家都收到少量自然线索，但资源只够验证一个市场。',
    prompt: '请给出市场选择框架和最先补的证据。',
    requirements: ['不只比较TAM', '纳入公司能力和合规', '说明证据等级'],
    framework: ['比较需求、竞争、可复用资源、合规、单位经济和验证效率', '定义一票否决项', '区分线索、意向、书面合作与交易', '选择最小可证伪市场，而非最大市场', '给出90天验证计划和退出条件'],
    pitfalls: ['市场大所以先做', '把英语普及等同本地化简单', '把少量线索当PMF'],
  },
  {
    id: 'q-gtm-plan', trackId: 'gtm', type: 'written', difficulty: '核心', duration: 45,
    title: '设计90天海外GTM计划',
    context: '一款面向中小企业的费用管理产品准备进入新加坡，目前没有本地品牌认知。',
    prompt: '请输出ICP、定位、渠道、定价假设、里程碑、指标和资源需求。',
    requirements: ['明确不服务谁', '渠道与ICP匹配', '包含Go／Stop闸门'],
    framework: ['市场与合规前提', '首期ICP、场景和购买委员会', '可量化价值主张', '直销、伙伴、内容或产品导向路径', '定价与包装假设', '0—30、31—60、61—90天实验', '获客、激活、成交、贡献与护栏指标'],
    pitfalls: ['只写传播渠道', '没有定价和销售责任', '里程碑都是内部动作'],
  },
  {
    id: 'q-launch-miss', trackId: 'gtm', type: 'scenario', difficulty: '进阶', duration: 30,
    title: '上线有流量但零转化，怎么救？',
    context: '新市场发布活动获得大量落地页访问，但核心套餐零销售；剩余预算还有40%。',
    prompt: '请判断问题、安排紧急动作，并说明如何向客户或管理层沟通。',
    requirements: ['区分曝光、点击和购买', '检查产品价值与价格', '说明预算调整权限'],
    framework: ['确认追踪和购买链路正常', '按产品、价格、日期、客群和渠道拆分', '对比替代方案和总价值', '访谈放弃用户或检查行为证据', '提出价格、产品、渠道或落地页调整', '保留小流量验证并设置预算切换阈值', '如实汇报原目标未达成和新假设'],
    pitfalls: ['继续加曝光', '隐藏零销售', '把调整后的整体增长归因于原套餐'],
  },
  {
    id: 'q-partner-model', trackId: 'globalization', type: 'interview', difficulty: '基础', duration: 12,
    title: '如何评估一个海外渠道伙伴？',
    context: '一家本地内容平台声称拥有大量用户，希望收固定费再按效果收费。',
    prompt: '你会问什么，如何设计首轮合作？',
    requirements: ['验证受众与流量质量', '明确数据归因', '控制固定费风险'],
    framework: ['受众地域、意图、触达渠道和历史效果', '与ICP重合度', '展示、点击、订单、取消和贡献数据', '品牌、交易、售后和数据责任', '小范围区域或品类测试', '固定费上限＋效果计费', '书面资源、停止条件和复盘节奏'],
    pitfalls: ['只看总粉丝量', '默认流量免费或稳定', '没有订单回传和取消率'],
  },
  {
    id: 'q-pipeline-forecast', trackId: 'globalization', type: 'written', difficulty: '核心', duration: 35,
    title: '从10个账户做本月销售预测',
    context: '你接手10个目标账户，分别处于初次接触、需求确认、方案、商务和签约阶段。',
    prompt: '请定义阶段退出条件、加权预测、Commit与Best Case，并说明最大风险。',
    requirements: ['客户行为决定阶段', '区分活动和进展', '为每单写明确下一步'],
    framework: ['定义阶段及概率', '逐单记录金额、预计日期、决策链和阻碍', 'Commit只放有客户承诺且风险可控的商机', 'Best Case包含尚有一个关键条件待解决的商机', '按历史偏差校准概率', '复盘滑单原因'],
    pitfalls: ['发过方案就算高概率', '所有商机都按统一概率', '没有日期和下一步'],
  },
  {
    id: 'q-kyb-block', trackId: 'globalization', type: 'scenario', difficulty: '进阶', duration: 25,
    title: 'KYB卡住大促上线，如何处理？',
    context: '一家跨境电商商户希望一周内上线收款，但受益所有人材料不完整，合规团队不能放行。',
    prompt: '作为客户成功或商务负责人，你如何推进并管理预期？',
    requirements: ['不绕过合规', '明确客户与内部责任', '提供可行替代路径但不承诺审批'],
    framework: ['向客户说明缺失材料、原因、截止时间和潜在影响', '确认企业结构、受益所有人和文件有效性', '建立客户、CS、合规、产品责任表和升级路径', '评估是否有合规允许的分阶段能力或备用收款安排', '每日同步风险，但不替合规承诺结果', '上线后补对账、拒付和风控监控'],
    pitfalls: ['承诺一定按时通过', '为了大促跳过材料', '只转发合规邮件，不管理客户行动'],
  },
];
